name: Lint and check

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Check
        run: pnpm run check
