name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: pnpm
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint
      - name: Check
        run: pnpm run check
      - name: Build
        run: pnpm run build
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: "dist/"
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
